In [33]:
import sys
import numpy as np


class Node:
    def __init__(self, state, parent, move):
        self.state = state
        self.parent = parent
        self.move = move


class Visited:
    def __init__(self):
        self.visited = []

    def add(self, node):
		self.visited.append(node)

	def contains_state(self, state):
		return any((node.state[0] == state[0]).all() for node in self.visited)
	
	def remove(self):
		node = self.visited[-1]
		self.visited = self.visited[:-1]
		return node


class Explored(Visited):
	def remove(self):
		node = self.visited[0]
		self.visited = self.visited[1:]
		return node


class Puzzle:
	def __init__(self, start, startIndex, goal, goalIndex):
		self.start = [start, startIndex]
		self.goal = [goal, goalIndex] 
		self.solution = None

	def neighbors(self, state):
		mat, (row, col) = state
		results = []
		
		if row > 0:
			stateboard = np.copy(mat)
			stateboard[row][col] = stateboard[row - 1][col]
			stateboard[row - 1][col] = 0
			results.append(('up', [stateboard, (row - 1, col)]))
		if col > 0:
			stateboard = np.copy(mat)
			stateboard[row][col] = stateboard[row][col - 1]
			stateboard[row][col - 1] = 0
			results.append(('left', [stateboard, (row, col - 1)]))
		if row < 2:
			stateboard = np.copy(mat)
			stateboard[row][col] = stateboard[row + 1][col]
			stateboard[row + 1][col] = 0
			results.append(('down', [stateboard, (row + 1, col)]))
		if col < 2:
			stateboard = np.copy(mat)
			stateboard[row][col] = stateboard[row][col + 1]
			stateboard[row][col + 1] = 0
			results.append(('right', [stateboard, (row, col + 1)]))

		return results

	def print(self):
		solution = self.solution if self.solution is not None else None
		print("Start State:\n", self.start[0], "\n")
		print("Goal State:\n",  self.goal[0], "\n")
		print("\nStates Explored: ", self.num_explored, "\n")
		print("Solution:\n ")
		for move, state in zip(solution[0], solution[1]):
			print(state[0], "\n")

	def does_not_contain_state(self, state):
		for st in self.explored:
			if (st[0] == state[0]).all():
				return False
		return True
	
	def solve(self):
		self.num_explored = 0

		start = Node(state=self.start, parent=None, move=None)
		marked = Explored()
		marked.add(start)

		self.explored = [] 

		while True:
			node = marked.remove()
			self.num_explored += 1

			if (node.state[0] == self.goal[0]).all():
				moves = []
				states = []
				while node.parent is not None:
					moves.append(node.move)
					states.append(node.state)
					node = node.parent
				moves.reverse()
				states.reverse()
				self.solution = (moves,  states)
				return

			self.explored.append(node.state)

			for move, state in self.neighbors(node.state):
				if not marked.contains_state(state) and self.does_not_contain_state(state):
					child = Node(state=state, parent=node, move=move)
					marked.add(child)


start = np.array([[1, 2, 3], [8, 0, 4], [7, 6, 5]])
goal = np.array([[2, 8, 1], [0, 4, 3], [7, 6, 5]])


startIndex = (1, 1)
goalIndex = (1, 0)


p = Puzzle(start, startIndex, goal, goalIndex)
p.solve()
p.print()

Start State:
 [[1 2 3]
 [8 0 4]
 [7 6 5]] 

Goal State:
 [[2 8 1]
 [0 4 3]
 [7 6 5]] 


States Explored:  358 

Solution:
 
[[1 0 3]
 [8 2 4]
 [7 6 5]] 

[[0 1 3]
 [8 2 4]
 [7 6 5]] 

[[8 1 3]
 [0 2 4]
 [7 6 5]] 

[[8 1 3]
 [2 0 4]
 [7 6 5]] 

[[8 1 3]
 [2 4 0]
 [7 6 5]] 

[[8 1 0]
 [2 4 3]
 [7 6 5]] 

[[8 0 1]
 [2 4 3]
 [7 6 5]] 

[[0 8 1]
 [2 4 3]
 [7 6 5]] 

[[2 8 1]
 [0 4 3]
 [7 6 5]] 

